# Generated by Django 3.2.3 on 2021-06-07 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210604_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': ('продукт',), 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': ('категория',), 'verbose_name_plural': 'категории'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantiy',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now, verbose_name='описание'),
            preserve_default=False,
        ),
    ]
